# Generated by Django 4.1.7 on 2023-03-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0007_complaintview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintview',
            old_name='sid',
            new_name='societymember_id',
        ),
    ]
