# Generated by Django 4.1.7 on 2023-03-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0008_rename_sid_complaintview_societymember_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintview',
            name='societymember_id',
        ),
    ]
